import streamlit as st
import uuid
from modules.prompt import sanitize_prompt
from modules.image_gen import generate_image
from modules.upload import upload_file_to_s3
from streamtoolkit_omkar.auth.streamlit_guard import token_input_box, get_user_from_token_ui

st.set_page_config(page_title="GPT-4o S3 Wrapper", layout="centered")
st.title("🧠 GPT-4o Image Wrapper + Upload + S3")

token = token_input_box()
user = get_user_from_token_ui(token)


if user:
    uploaded_file = st.file_uploader("📤 Upload an image (optional)", type=["png", "jpg", "jpeg"])
    prompt = st.text_area("Or enter a text prompt")

    if st.button("Generate / Upload") and (prompt or uploaded_file):
        with st.spinner("Processing..."):
            if uploaded_file:
                file_id = f"user_uploads/{user['username']}/{uuid.uuid4()}.png"
                url = upload_file_to_s3(uploaded_file, file_id)
                st.success(f"Uploaded to S3: {url}")
            if prompt:
                final_prompt = sanitize_prompt(prompt)
                img_url = generate_image(final_prompt)
                st.image(img_url, caption="Generated by GPT-4o", use_container_width=True)
